import random
random.seed(42)
print([random.random() for _ in range(3)])
random.seed(42)
print([random.randint(1, 100) for _ in range(5)])
random.seed(7)
print(random.choice(["a", "b", "c"]), random.randrange(10), random.randrange(0, 100, 5), random.uniform(1, 2))
random.seed(3)
l = list(range(10))
random.shuffle(l)
print(l, random.sample(range(100), 5), random.sample(range(10000), 3), random.getrandbits(40))
random.seed(2 ** 70 + 5)
print(random.random())
random.seed(-5)
print(random.randint(-10, 10), random.choice("xyz"))
