import turtle
screen = turtle.Screen()
screen.mode("logo")
t = turtle.Turtle()
print(t.heading())
t.forward(50)
t.right(90)
t.forward(50)
t.setheading(180)
t.forward(20)
print(t.pos(), t.heading())
t.radians()
t.left(3.14159 / 2)
print(round(t.heading(), 4))
turtle.done()
