import turtle
t = turtle.Turtle()
t.forward(50)
t.teleport(20, 30)
t.forward(40)
t.clear()
t.circle(20)
t.reset()
t.left(30)
t.forward(25)
t.begin_fill()
t.circle(30)
t.teleport(-80, -80)
t.forward(20)
t.end_fill()
print(t.pos(), t.filling())
turtle.done()
