import turtle
t = turtle.Turtle()
t.shape("turtle")
t.color("green")
t.stamp()
t.forward(60)
t.shape("circle")
t.shapesize(2, 1, 3)
t.stamp()
t.left(45)
t.forward(60)
t.write("Hello", align="center", font=("Arial", 16, "bold"))
t.penup()
t.goto(-150, -100)
t.write("PyPlay turtle", move=True)
t.write("left", align="left")
t.hideturtle()
print(t.shape(), t.shapesize(), t.isvisible(), t.pos())
turtle.done()
